version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo "Build and test your code here"
  post_build:
    commands:
      - echo "Post-build actions go here"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
