version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Use the available Java 17 version (corretto17)
    commands:
      - echo "Installing corretto(OpenJDK) version 17 ..."
      - export JAVA_HOME="$JAVA_17_HOME"
      - export JRE_HOME="$JRE_17_HOME"
      - export JDK_HOME="$JDK_17_HOME"
      - |
        for tool_path in "$JAVA_HOME"/bin/*;
        do
          tool=`basename "$tool_path"`;
          if [ $tool != 'java-rmi.cgi' ];
          then
            rm -f /usr/bin/$tool /var/lib/alternatives/$tool \
              && update-alternatives --install /usr/bin/$tool $tool $tool_path 20000;
          fi;
        done

# Add other phases (pre_build, build, post_build) and artifacts and cache sections as needed
