name: CI/CD with CodeBuild

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: Amazon Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build and test steps here

      - name: Deploy to AWS CodeBuild
        run: |
          aws codebuild start-build --project test-project
        env:
          AWS_DEFAULT_REGION: us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIA3WPZ424TOBRECH5V }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.kKypLAuLGekY0gnsrCAI/12FAMdknx3l6CJfqy1L }}
